// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/gdpr/customers_data_request": {
    params: {};
  };
  "/webhooks/gdpr/customers_redact": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/gdpr/shop_redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/judgeme/review": {
    params: {};
  };
  "/api/cron/auto-post": {
    params: {};
  };
  "/instagram/callback": {
    params: {};
  };
  "/instagram/redirect": {
    params: {};
  };
  "/instagram/connect": {
    params: {};
  };
  "/judgeme/callback": {
    params: {};
  };
  "/judgeme/redirect": {
    params: {};
  };
  "/judgeme/connect": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/instagram/disconnect": {
    params: {};
  };
  "/app/judgeme/disconnect": {
    params: {};
  };
  "/app/reviews": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/gdpr/customers_data_request" | "/webhooks/gdpr/customers_redact" | "/webhooks/app/scopes_update" | "/webhooks/gdpr/shop_redact" | "/webhooks/app/uninstalled" | "/webhooks/judgeme/review" | "/api/cron/auto-post" | "/instagram/callback" | "/instagram/redirect" | "/instagram/connect" | "/judgeme/callback" | "/judgeme/redirect" | "/judgeme/connect" | "/auth/login" | "/auth/*" | "/app" | "/app/instagram/disconnect" | "/app/judgeme/disconnect" | "/app/reviews";
  };
  "routes/webhooks.gdpr.customers_data_request.tsx": {
    id: "routes/webhooks.gdpr.customers_data_request";
    page: "/webhooks/gdpr/customers_data_request";
  };
  "routes/webhooks.gdpr.customers_redact.tsx": {
    id: "routes/webhooks.gdpr.customers_redact";
    page: "/webhooks/gdpr/customers_redact";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.gdpr.shop_redact.tsx": {
    id: "routes/webhooks.gdpr.shop_redact";
    page: "/webhooks/gdpr/shop_redact";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.judgeme.review.tsx": {
    id: "routes/webhooks.judgeme.review";
    page: "/webhooks/judgeme/review";
  };
  "routes/api.cron.auto-post.tsx": {
    id: "routes/api.cron.auto-post";
    page: "/api/cron/auto-post";
  };
  "routes/instagram.callback.tsx": {
    id: "routes/instagram.callback";
    page: "/instagram/callback";
  };
  "routes/instagram.redirect.tsx": {
    id: "routes/instagram.redirect";
    page: "/instagram/redirect";
  };
  "routes/instagram.connect.tsx": {
    id: "routes/instagram.connect";
    page: "/instagram/connect";
  };
  "routes/judgeme.callback.tsx": {
    id: "routes/judgeme.callback";
    page: "/judgeme/callback";
  };
  "routes/judgeme.redirect.tsx": {
    id: "routes/judgeme.redirect";
    page: "/judgeme/redirect";
  };
  "routes/judgeme.connect.tsx": {
    id: "routes/judgeme.connect";
    page: "/judgeme/connect";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/instagram/disconnect" | "/app/judgeme/disconnect" | "/app/reviews";
  };
  "routes/app.instagram.disconnect.tsx": {
    id: "routes/app.instagram.disconnect";
    page: "/app/instagram/disconnect";
  };
  "routes/app.judgeme.disconnect.tsx": {
    id: "routes/app.judgeme.disconnect";
    page: "/app/judgeme/disconnect";
  };
  "routes/app.reviews.tsx": {
    id: "routes/app.reviews";
    page: "/app/reviews";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.gdpr.customers_data_request": typeof import("./app/routes/webhooks.gdpr.customers_data_request.tsx");
  "routes/webhooks.gdpr.customers_redact": typeof import("./app/routes/webhooks.gdpr.customers_redact.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.gdpr.shop_redact": typeof import("./app/routes/webhooks.gdpr.shop_redact.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.judgeme.review": typeof import("./app/routes/webhooks.judgeme.review.tsx");
  "routes/api.cron.auto-post": typeof import("./app/routes/api.cron.auto-post.tsx");
  "routes/instagram.callback": typeof import("./app/routes/instagram.callback.tsx");
  "routes/instagram.redirect": typeof import("./app/routes/instagram.redirect.tsx");
  "routes/instagram.connect": typeof import("./app/routes/instagram.connect.tsx");
  "routes/judgeme.callback": typeof import("./app/routes/judgeme.callback.tsx");
  "routes/judgeme.redirect": typeof import("./app/routes/judgeme.redirect.tsx");
  "routes/judgeme.connect": typeof import("./app/routes/judgeme.connect.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.instagram.disconnect": typeof import("./app/routes/app.instagram.disconnect.tsx");
  "routes/app.judgeme.disconnect": typeof import("./app/routes/app.judgeme.disconnect.tsx");
  "routes/app.reviews": typeof import("./app/routes/app.reviews.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};