// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/judgeme/callback": {
    params: {};
  };
  "/judgeme/redirect": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/judgeme/disconnect": {
    params: {};
  };
  "/app/judgeme/connect": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/judgeme/callback" | "/judgeme/redirect" | "/auth/login" | "/auth/*" | "/app" | "/app/judgeme/disconnect" | "/app/judgeme/connect" | "/app/additional";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/judgeme.callback.tsx": {
    id: "routes/judgeme.callback";
    page: "/judgeme/callback";
  };
  "routes/judgeme.redirect.tsx": {
    id: "routes/judgeme.redirect";
    page: "/judgeme/redirect";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/judgeme/disconnect" | "/app/judgeme/connect" | "/app/additional";
  };
  "routes/app.judgeme.disconnect.tsx": {
    id: "routes/app.judgeme.disconnect";
    page: "/app/judgeme/disconnect";
  };
  "routes/app.judgeme.connect.tsx": {
    id: "routes/app.judgeme.connect";
    page: "/app/judgeme/connect";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/judgeme.callback": typeof import("./app/routes/judgeme.callback.tsx");
  "routes/judgeme.redirect": typeof import("./app/routes/judgeme.redirect.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.judgeme.disconnect": typeof import("./app/routes/app.judgeme.disconnect.tsx");
  "routes/app.judgeme.connect": typeof import("./app/routes/app.judgeme.connect.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};